name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  testing:
    name: Compose Testing
    runs-on: macos-latest
    steps:
    - name: Compose tests
      uses: ReactiveCircus/android-emulator-runner@v2.26.0
      with:
        java-version: 12
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew :app:composeapp:connectedCheck
  release:
    name: Release NotyKT Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant Permission to Execute
        run: chmod +x gradlew
        working-directory: noty-android

      - name: Build APKs ⚙️🛠
        run: bash ./gradlew assemble
        working-directory: noty-android

      - name: Create Release ✅
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload NotyKT Simple App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: noty-android/app/simpleapp/build/outputs/apk/stage/debug/simpleapp-stage-debug.apk
          asset_name: noty-android-simple.apk
          asset_content_type: application/apk
          
      - name: Upload NotyKT Compose App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: noty-android/app/composeapp/build/outputs/apk/stage/debug/composeapp-stage-debug.apk
          asset_name: noty-android-compose.apk
          asset_content_type: application/apk
